### ISSUE TITLE
Please set rollup as peerDependency

### ISSUE THREAD

**Issue by btd** [Permutatrix/rollup-stream#23] opened 2017-10-02 11:42 UTC
There are a lot of good reasons do not include rollup to dependencies and allow user to decide which version he want to use.

**Comment by lemmabit** [comment] 2017-10-02 20:10
Duplicate of #12. You can use any version of Rollup you like by specifying the `rollup` option; see my response to #12. I think peer dependencies were a bad idea.

The dependency on Rollup is provided for convenience, but I am planning to remove it in v2.0.0 for a number of reasons. After that, manual injection of the dependency will be mandatory.

**Closed as completed by lemmabit** 2017-10-02 20:10 UTC
Labels: duplicate
